name: Snake Game

on:
  schedule:
    - cron: "*/30 * * * *"  # This commits every 30 minutes
  workflow_dispatch:

jobs:
  game:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Play Snake Game
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

