name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Ensure dist directory exists
      - name: Ensure dist directory exists
        run: |
          mkdir -p dist

      # Snake Animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: tarikbinaziz
          svg_out_path: dist/github-contribution-grid-snake.svg

      # List files in dist directory to verify
      - name: List files in dist directory
        run: ls -l dist

      # Push to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
